export const teamsArray = [
  { name: "Alianza Lima", slug: "alianza", minutes: 0, players: [] },
  { name: "Universitario", slug: "universitario", minutes: 0, players: [] },
  { name: "Sporting Cristal", slug: "cristal", minutes: 0, players: [] },
  {
    name: "Comerciantes Unidos",
    slug: "comerciantes-unidos",
    minutes: 0,
    players: [],
  },
  { name: "Los Chankas", slug: "chankas", minutes: 0, players: [] },
  { name: "Melgar", slug: "melgar", minutes: 0, players: [] },
  { name: "Cusco FC", slug: "cusco", minutes: 0, players: [] },
  { name: "Sport Huancayo", slug: "huancayo", minutes: 0, players: [] },
  { name: "Deportivo Garcilaso", slug: "garcilaso", minutes: 0, players: [] },
  { name: "Deportivo Binacional", slug: "binacional", minutes: 0, players: [] },
  { name: "Cienciano", slug: "cienciano", minutes: 0, players: [] },
  { name: "ADT", slug: "adt", minutes: 0, players: [] },
  { name: "Atlético Grau", slug: "grau", minutes: 0, players: [] },
  {
    name: "Alianza Atlético",
    slug: "alianza-atletico",
    minutes: 0,
    players: [],
  },
  { name: "Sport Boys", slug: "boys", minutes: 0, players: [] },
  {
    name: "Alianza Universidad",
    slug: "alianza-universidad",
    minutes: 0,
    players: [],
  },
  { name: "Juan Pablo II", slug: "juan-pablo", minutes: 0, players: [] },
  { name: "UTC", slug: "utc", minutes: 0, players: [] },
  { name: "Ayacucho FC", slug: "ayacucho", minutes: 0, players: [] },
];
