export const teams: {[key: string]: string} = {
    "alianza": "Alianza Lima",
    "universitario": "Universitario",
    "cristal": "Sporting Cristal",
    "comerciantes-unidos": "Comerciantes Unidos",
    "chankas": "Los Chankas",
    "melgar": "Melgar",
    "cusco": "Cusco FC",
    "huancayo": "Sport Huancayo",
    "garcilaso": "Deportivo Garcilaso",
    "binacional": "Deportivo Binacional",
    "cienciano": "Cienciano",
    "adt": "ADT",
    "grau": "Atlético Grau",
    "alianza-atletico": "Alianza Atlético",
    "boys": "Sport Boys",
    "alianza-universidad": "Alianza Universidad",
    "juan-pablo": "Juan Pablo II",
    "utc": "UTC",
    "ayacucho": "Ayacucho FC"
  }
